=== wmcc43/NcueIntro/src/android/edu/intro/mission/map_npc.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="map_npc" type="Map_npc"/>
		<xs:complexType name="Map_npc">
			<xs:sequence>
				<xs:element name="npc" type="Npc" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:complexType name="Npc">
			<xs:sequence>
				<xs:element name="mission" type="Mission" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type=" xs:int" use="required"/>
			<xs:attribute name="npc_name" xs:string use="required"/>
			<xs:attribute name="x" type="xs:int" use="required"/>
			<xs:attribute name="y" type="xs:int" use="required"/>
		</xs:complexType>
		<xs:complexType name="Mission">
			<xs:attribute name="mission_id" type="xs:int" use="required"/>
			<xs:attribute name="mission_sn" type="xs:int" use="required"/>
		</xs:complexType>
</xs:schema>

=== wmcc43/NcueIntro/src/android/edu/intro/mission/map_npc.xml
<?xml version="1.0" encoding="UTF-8"?>
<map_npc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="map_npc.xsd">
	<npc id="1" npc_name="001" x="0" y="0">
		<mission mission_id="100000" mission_sn="1"/>
	</npc>
	<npc id="2" npc_name="002" x="0" y="0">
		<mission mission_id="100000" mission_sn="2"/>
	</npc>
	<npc id="3" npc_name="003" x="0" y="0">
		<mission mission_id="100000" mission_sn="3"/>
	</npc>
	<npc id="4" npc_name="004" x="0" y="0">
		<mission mission_id="100000" mission_sn="4"/>
	</npc>
	<npc id="5" npc_name="005" x="0" y="0">
		<mission mission_id="100000" mission_sn="5"/>
	</npc>
	<npc id="6" npc_name="006" x="0" y="0">
		<mission mission_id="100000" mission_sn="6"/>
	</npc>
	<npc id="7" npc_name="007" x="0" y="0">
		<mission mission_id="100000" mission_sn="7"/>
	</npc>
	<npc id="8" npc_name="008" x="0" y="0">
		<mission mission_id="100000" mission_sn="8"/>
	</npc>
	<npc id="9" npc_name="009" x="0" y="0">
		<mission mission_id="100000" mission_sn="9"/>
	</npc>
	<npc id="10" npc_name="010" x="0" y="0">
		<mission mission_id="100000" mission_sn="10"/>
	</npc>
</map_npc>
